name: NodeCI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: setup graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Install dependencies
      run: npm ci && npm ls
      env:
        CI: 'true'
    - name: Lint
      run: npm run lint
      env:
        CI: 'true'
    - name: Build
      run: npm run build
      env:
        CI: 'true'
    - name: Unit Test
      run: npm test
      env:
        CI: 'true'
